#!/bin/sh
xset r rate 200 27
nitrogen --restore &
slstatus &
/usr/lib/lxpolkit/lxpolkit &
dunst &
setxkbmap pl
xmodmap ~/.config/xmodmap
export _JAVA_AWT_WM_NONREPARENTING=1
export EDITOR=/usr/bin/nvim
export CHROME_EXECUTABLE=/usr/bin/brave
export ZDOTDIR=$HOME/.config/zsh
export SHELL=/bin/zsh
export CC="/usr/bin/clang"
export CXX=/usr/bin/clang++
export JAVA_OPTS=''
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
export ANDROID_SDK_ROOT=~/Android/Sdk
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export PATH="$PATH:$ANDROID_SDK_ROOT/emulator"
export PATH="$PATH:$ANDROID_SDK_ROOT/platform-tools/"
export PATH="$PATH:$ANDROID_SDK_ROOT/tools/bin/"
export PATH="$PATH:$ANDROID_SDK_ROOT/tools/"
export PATH="$PATH:$ANDROID_SDK_ROOT/emulator:$PATH"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:$HOME/.cargo/bin/"
export PATH="$PATH:$HOME/scripts/"
export PATH="$PATH:$HOME/.local/bin"
export QT_QPA_PLATFORMTHEME=gtk2
export TERMINAL="/usr/local/bin/st"
export TERM="/usr/local/bin/st"

exec dwm
