return require("lazy").setup({
    "catppuccin/nvim",
    "tpope/vim-commentary",
    "nvim-lua/popup.nvim",
    "unblevable/quick-scope",
    "easymotion/vim-easymotion",
    "tpope/vim-surround",
    "qpkorr/vim-bufkill",
    "nvim-lua/plenary.nvim",
    "stevearc/dressing.nvim",
    "nvim-lualine/lualine.nvim",
    "nvim-tree/nvim-web-devicons",
    "HiPhish/rainbow-delimiters.nvim",
    "lukas-reineke/indent-blankline.nvim",
    "NvChad/nvim-colorizer.lua",
    "tpope/vim-repeat",
    { "nvim-treesitter/nvim-treesitter", cmd = "TSUpdate" },
    { "windwp/nvim-autopairs",           config = function() require('nvim-autopairs').setup {} end, },
})
